import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUp, Plus, MessageSquare, BookOpen, Activity, ShieldCheck, LogOut, ChevronDown, ThumbsUp, ThumbsDown, Cloud, ArrowRight } from 'lucide-react';
import './style.css';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
const API=import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
function App(){
 const [token,setToken]=useState(''),[draftToken,setDraftToken]=useState(''),[page,setPage]=useState('chat');
 const [threads,setThreads]=useState([]),[thread,setThread]=useState(null),[messages,setMessages]=useState([]);
 const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[docs,setDocs]=useState([]),[monitor,setMonitor]=useState(null),[markdown,setMarkdown]=useState(''),[notice,setNotice]=useState('');
 async function api(path,body,auth=token){
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),35000);
  try {const res=await fetch(API+path,{method:body===undefined?'GET':'POST',headers:{'Authorization':'Bearer '+auth,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:controller.signal});
   const data=await res.json();if(!res.ok)throw new Error(data.error?.message || data.detail?.message || `Request failed (${res.status})`);return data;
  } finally {clearTimeout(timer);}
 }
 async function signIn(e){e.preventDefault();setError('');try{const rows=await api('/threads',undefined,draftToken.trim());setToken(draftToken.trim());setDraftToken('');setThreads(rows);}catch(e){setError(e.message);}}
 function signOut(){setToken('');setThreads([]);setMessages([]);setThread(null);setMonitor(null);setDocs([]);setError('');}
 async function switchThread(id){setError('');try{const data=await api('/threads/'+id);setThread(id);setMessages(data.messages.map(m=>m.role==='assistant'?{role:'assistant',...m.payload}:{role:m.role,answer:m.content}));}catch(e){setError(e.message);}}
 async function refreshPage(next){setPage(next);setError('');setNotice('');try{if(next==='documents')setDocs(await api('/documents'));if(next==='monitoring')setMonitor(await api('/monitoring'));}catch(e){setError(e.message);}}
 async function send(e){e?.preventDefault();if(!input.trim()||busy)return;const question=input;setInput('');setBusy(true);setError('');setMessages(m=>[...m,{role:'user',answer:question}]);try{const answer=await api('/chat',{message:question,thread_id:thread});setThread(answer.thread_id);setMessages(m=>[...m,{role:'assistant',...answer}]);setThreads(await api('/threads'));}catch(e){setError(e.message+' Your message may not have been processed.');}finally{setBusy(false);}}
 async function feedback(id,helpful){try{await api('/feedback',{response_id:id,helpful});setNotice('Thank you — your feedback was recorded.');}catch(e){setError(e.message);}}
 async function ingest(e){e.preventDefault();setBusy(true);setError('');try{await api('/documents',{markdown});setMarkdown('');setDocs(await api('/documents'));setNotice('Document indexed.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="app"><aside><div className="brand"><span className="logo"><Cloud size={24}/></span><div>SupportFlow<small>CLOUDBOX WORKSPACE</small></div></div><div className="workspace"><span className="avatar">CB</span><div>CloudBox support<small>Evidence-led assistance</small></div><ShieldCheck size={17}/></div><div className="nav-label">WORKSPACE</div><nav>{[['chat',MessageSquare,'Conversations'],['documents',BookOpen,'Knowledge base'],['monitoring',Activity,'Monitoring']].map(([key,Icon,label])=><button key={key} className={page===key?'active':''} onClick={()=>refreshPage(key)} disabled={!token||busy}><Icon size={18}/>{label}</button>)}</nav><div className="thread-heading"><span>YOUR CONVERSATIONS</span><button title="New conversation" disabled={!token||busy} onClick={()=>{setThread(null);setMessages([]);setPage('chat');}}><Plus size={17}/></button></div><div className="thread-list">{threads.map((t,i)=><button disabled={busy} className={thread===t.thread_id?'selected':''} key={t.thread_id} onClick={()=>switchThread(t.thread_id)}><MessageSquare size={14}/>{t.title==='New conversation'?`Conversation ${i+1}`:t.title}</button>)}{!threads.length&&<p>Your conversations will appear here.</p>}</div><div className="side-bottom"><ShieldCheck size={18}/><span>Private by design<small>Scoped to your account</small></span>{token&&<button onClick={signOut} title="Sign out"><LogOut size={18}/></button>}</div></aside>
 <main><header><div><span className="breadcrumb">Workspace / </span>{page==='chat'?'Conversations':page==='documents'?'Knowledge base':'Monitoring'}</div><div className="header-meta"><span className="creator-credit">Built by Rana Refaat</span><span className="badge"><span/>CloudBox support</span></div></header><div className="mobile-nav">{token&&<> {["chat","documents","monitoring"].map(x=><button key={x} onClick={()=>refreshPage(x)} disabled={busy}>{x}</button>)}<button disabled={busy} onClick={()=>{setThread(null);setMessages([]);setPage("chat");}}>New chat</button><button onClick={signOut}>Sign out</button></>}</div><div className="content">
 {error&&<div role="alert" className="alert">{error}</div>}{notice&&<div role="status" className="notice">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
 {!token?<section className="welcome"><div className="eyebrow">SUPPORT, WITH EVIDENCE</div><h1>A clear path<br/>to your next step.</h1><p>Get grounded answers, guided troubleshooting, and a direct path to the right support team.</p><form onSubmit={signIn} className="login"><label htmlFor="token">Secure session token</label><input id="token" type="password" value={draftToken} onChange={e=>setDraftToken(e.target.value)} placeholder="Paste your issued session token" autoComplete="off" required/><button className="primary">Connect to workspace <ArrowRight size={17}/></button><small>Session tokens stay in memory. Never enter your CloudBox password or a verification code here.</small></form></section>:page==='chat'?<>
 {!messages.length?<section className="welcome"><div className="welcome-icon"><Cloud size={30}/></div><div className="eyebrow">YOUR CLOUDBOX ASSISTANT</div><h1>Let’s work through it.</h1><p>Ask a question. Follow the evidence.<br/>Find the next step that makes sense.</p><div className="prompts">{[['Compare plans','What is the difference between the Standard and Team plans?'],['Fix a sync issue','My files are duplicated after I worked offline. What should I do?'],['Check an order','Please check order ord_7001 and tell me the amount.'],['Get support','I think someone accessed my account. What do I do?']].map(([title,q])=><button key={title} onClick={()=>setInput(q)}><span>{title}<small>{q}</small></span><ArrowRight size={17}/></button>)}</div></section>:<div className="conversation">{messages.map((m,i)=><article className={'message '+m.role} key={m.response_id||i}><div className="message-label">{m.role==='user'?'You':'SupportFlow'}{m.route&&<span>{m.route.replaceAll('_',' ')}</span>}</div><div className="answer">{m.role==="assistant"?<ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml>{m.answer}</ReactMarkdown>:m.answer}</div>{m.needs_escalation&&<div className="escalation"><ShieldCheck size={16}/>{m.ticket_id?`Escalated · ${m.ticket_id}`:'Escalation required · ticket not created'}</div>}{m.citations?.length>0&&<div className="sources"><h4>Sources · {m.citations.length}</h4>{m.citations.map(c=><details key={c.chunk_id}><summary><BookOpen size={14}/>{c.title}<small>v{c.version} · {c.trust_level}</small></summary><pre>{c.content}</pre><small>{c.source_path} · relevance {c.score.toFixed(3)} (not a confidence probability)</small></details>)}</div>}{m.tool_events&&<details className="tool-log"><summary><Activity size={14}/>Tool activity · {m.tool_events.length}<ChevronDown size={14}/></summary>{m.tool_events.map((t,j)=><div key={j}><span className={t.ok?'ok':'failed'}>{t.ok?'OK':'ERROR'}</span><b>{t.name}</b><small>{t.latency_ms} ms</small>{t.error&&<p>{t.error.message}</p>}</div>)}</details>}{m.response_id&&<div className="message-footer"><span>{m.latency_ms} ms · trace {m.trace_id.slice(0,8)}</span><button onClick={()=>feedback(m.response_id,true)} title="Helpful"><ThumbsUp size={15}/></button><button onClick={()=>feedback(m.response_id,false)} title="Not helpful"><ThumbsDown size={15}/></button></div>}</article>)}{busy&&<div className="thinking">Checking the evidence…</div>}</div>}
 <div className="composer-wrap"><form onSubmit={send} className="composer"><textarea aria-label="Message" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}} placeholder="How can we help with CloudBox?" maxLength={4000} rows={2} disabled={busy}/><button className="primary" disabled={busy||!input.trim()} title="Send message"><ArrowUp size={20}/></button></form><div className="composer-note"><ShieldCheck size={12}/> Please don’t share passwords, verification codes, or payment card details.</div></div>
 </>:page==='documents'?<section className="data-page"><div className="eyebrow">CONTROLLED KNOWLEDGE</div><h1>The source of every answer.</h1><p>Official documentation, versioned and searchable.</p><div className="doc-grid">{docs.map(d=><article key={d.doc_id+d.version}><BookOpen/><h3>{d.title}</h3><p>{d.product} · v{d.version}</p><span className="tag">{d.trust_level}</span><small>{d.doc_id}</small></article>)}</div><form className="ingest" onSubmit={ingest}><h2>Add a document</h2><p>Administrator access required. Include all YAML metadata fields.</p><textarea aria-label="Document markdown" rows={9} value={markdown} onChange={e=>setMarkdown(e.target.value)} placeholder={'---\ndoc_id: new_policy\ntitle: New policy\nproduct: CloudBox\nversion: 2026-09\nsource_type: support_policy\ntrust_level: official\n---\n\n# Policy\n...'} required/><button className="primary" disabled={busy}>Index document</button></form></section>:<section className="data-page"><div className="eyebrow">OBSERVABILITY</div><h1>See how support is working.</h1><p>Recent activity within your authenticated account.</p><button onClick={()=>refreshPage('monitoring')}>Refresh metrics</button>{monitor&&<><div className="metrics">{[['Requests',monitor.requests],['Mean latency',Math.round(monitor.mean_latency_ms)+' ms'],['Escalation rate',Math.round(monitor.escalation_rate*100)+'%'],['Tool error rate',Math.round(monitor.error_rate*100)+'%']].map(([k,v])=><article key={k}><small>{k}</small><strong>{v}</strong></article>)}</div><div className="table-wrap"><table><thead><tr><th>Trace</th><th>Route</th><th>Latency</th><th>Tool status</th></tr></thead><tbody>{monitor.recent.map(r=><tr key={r.request_id}><td><code>{r.trace_id}</code></td><td>{r.route}</td><td>{r.latency_ms} ms</td><td>{r.error?'Error handled':'OK'}</td></tr>)}</tbody></table></div>{!monitor.requests&&<p>No requests yet. Start a conversation to see metrics.</p>}</>}</section>}
 </div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
